spring:
  r2dbc:
    url: r2dbc:postgresql://${db.host}/users
    username: ${db.user}
    password: ${db.password}

  datasource:
    url: jdbc:postgresql://${db.host}/users
    username: ${db.user}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET app.mock_data TO '${MOCK_DATA_ENABLED:false}'


  flyway:
    enabled: true
    url: jdbc:postgresql://${db.host}/users
    user: ${db.user}
    password: ${db.password}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${security.host}/realms/portfolios
          jwk-set-uri: ${security.host}/realms/portfolios/protocol/openid-connect/certs
server:
  port: 8081

keycloak:
  realm: portfolios
  auth-server-url: ${security.host}
  client-id: user-mgmt-client
  client-secret: ${KC_CLIENT_SECRET}

https: false

db:
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    name: users
    host: localhost:5432

security:
  host: http://localhost:8080