spring:
  r2dbc:
    url: r2dbc:postgresql://user-db:5432/users
    username: ${db.user}
    password: ${db.password}

  datasource:
    url: jdbc:postgresql://user-db:15432/users
    username: ${db.user}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: jdbc:postgresql://user-db:5432/users
    user: ${db.user}
    password: ${db.password}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: localhost:8080/realms/portfolios
          jwk-set-uri: localhost:8080/realms/portfolios/protocol/openid-connect/certs
server:
  port: 8081

keycloak:
  realm: portfolios
  auth-server-url: http://localhost:8080
  client-id: user-mgmt-client
  client-secret: ${KC_CLIENT_SECRET}

https: false

db:
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    name: users

