spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/users
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  datasource:  # Flyway używa klasycznego JDBC
    url: jdbc:postgresql://localhost:5432/users
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/users
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true